name: AWS SSM Send-Command Example

on: 
  push
jobs:
  
  test: 
    runs-on: ubuntu-latest
    if: 
      contains('
      refs/heads/main',github.ref)
    steps:
    - name: Code pushed in main branch
      run: echo "Pushed code into main branch"
    - uses: actions/checkout@v2 
    - name: Deploy in EC2  
      run: |
        # echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        # ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
        
        #   #Now we have got the access of EC2 and we will start the deploy .
        #   cd /home/ec2-user/docker-aws-ec2 &&
        #   git checkout main &&
        #   git fetch --all &&
        #   git reset --hard origin/main &&
        #   git pull origin main &&
        #   docker-compose -f docker-compose.yml up -d --build 
        echo "This is the working directory that we got from deploy in ec2 action" &&
        pwd
      env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME : ${{ secrets.HOST_NAME  }}
          USER_NAME : ${{ secrets.USER_NAME  }}
    - name: Checkout the files
      uses: actions/checkout@v2

    - name: Deploy to Server 1
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_NAME }}
        REMOTE_USER: ${{ secrets.USER_NAME }}
        TARGET: ${{ secrets.TARGET_DIR }}
    - name: Checking the Code inside the ec2 
      run: echo "The Directory ---- > \n" && pwd

      

  demo:
    runs-on: ubuntu-latest
    if: 
      contains('
      refs/heads/dev',github.ref)
    steps:
    - name: Code pushed into the development branch 
      run: echo "Code pushed into development branch"
    

  # imagebuild:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Get current date
  #     id: date
  #     run: echo "::set-output name=date::$(date +'doctor-strange-%Y-%m-%dT%H-%M-%S')"
  #   - name: Test with environment variables
  #     run: echo $TAG_NAME - $RELEASE_NAME
  #     env:
  #       TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
  #       RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
  #   - uses: actions/checkout@v2
  #   - name: docker login
  #     env:
  #       DOCKER_USER: ${{secrets.DOCKER_USER}}
  #       DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  #     run: |
  #       docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  #   - name: Build the Docker image
  #     run: docker build . --file Dockerfile --tag bertoxious/check-prod-dev:latest

  #   - name: Docker Push
  #     run: docker push ${{secrets.DOCKER_USER}}/check-prod-dev:latest
      # - name: Checkout the files
      #   uses: actions/checkout@v2

      # - name: Deploy to Server 1
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      #     REMOTE_HOST: ${{ secrets.HOST_DNS }}
      #     REMOTE_USER: ${{ secrets.USERNAME }}
      #     TARGET: ${{ secrets.TARGET_DIR }}

